-- ⚠️  Dieses File ist NICHT mehr die Quelle der Wahrheit und darf NICHT mehr
--     gegen die Datenbank ausgeführt werden (die alte Version enthielt DROPs,
--     die Produktionsdaten löschen konnten).
--
-- Das Schema lebt jetzt in versionierten, idempotenten Migrationen:
--     migrations/0001_init.sql   ← Baseline (alle Tabellen, CREATE ... IF NOT EXISTS)
--     migrations/0002_*.sql      ← additive Änderungen danach
--
-- Ausrollen (idempotent, sicher gegen bestehende DB):
--     wrangler d1 migrations apply wuerfelpoker --remote      (Produktion)
--     wrangler d1 migrations apply wuerfelpoker --local       (lokal)
--
-- Lokales Komplett-Zurücksetzen (LÖSCHT DATEN, nur Dev):
--     wrangler d1 execute wuerfelpoker --local --file=./reset-dev.sql
--     danach: wrangler d1 migrations apply wuerfelpoker --local
