// ====================================================================
// Wer weiß's? — REINE Spiel-Logik (keine Durable-Object-/Runtime-Abhängigkeit).
// Ausgelagert aus dem QuizRoom, damit sie ohne laufenden Worker unit-testbar
// ist (tests/quiz.test.mjs). Der QuizRoom importiert diese Funktionen; hier
// steht NUR deterministische Logik + der Fragensatz.
//
// Konvention Fragensatz: die RICHTIGE Antwort steht immer an a[0] (c:0) —
// das macht das Autoren fehlerarm. Der QuizRoom mischt die Optionen pro Spiel
// über shuffleOptions(), damit die Lösung nicht immer an derselben Stelle steht.
// de-AT-Vokabular, bewusst eindeutige Fragen (keine strittigen Fakten).
// ====================================================================

export const Q_TURN = 20;    // Sekunden pro Frage
export const Q_REVEAL = 6;   // Auflösung anzeigen (kurze Ergebnis-Übersicht)
export const Q_ROUNDS = 10;  // Standard-Fragenzahl
export const Q_ROUND_CHOICES = [5, 10, 15, 20];

// Schwierigkeits-Stufen (0 = alle). Die Stufe leitet sich aus der Kategorie ab
// (Q_CAT_DIFF); optional kann eine einzelne Frage per `d`-Feld überschreiben.
// So ist der Filter sofort nutzbar, ohne alle Fragen einzeln zu markieren.
export const Q_DIFF_CHOICES = [0, 1, 2, 3];
export const Q_DIFF_LABELS = { 0: "Alle", 1: "Leicht", 2: "Mittel", 3: "Schwer" };
export const Q_CAT_DIFF = {
  allgemein: 1, natur: 1, essen: 1, film: 1,
  geografie: 2, sport: 2, kultur: 2, oesterreich: 2,
  wissenschaft: 3, geschichte: 3, schwer: 3,
};

// Bonus für aufeinanderfolgende richtige Antworten (Streak). Ab 2 in Folge, in
// 10er-Schritten, gedeckelt bei +50 — belohnt Konstanz, ohne Tempo zu entwerten.
export function streakBonus(streak) {
  return streak >= 2 ? Math.min(50, (streak - 1) * 10) : 0;
}

// q = Frage, a = [richtig, falsch, falsch, falsch], c = Index der Lösung (immer 0).
export const Q_CATS = {
  allgemein: [
    { q: "Wie viele Minuten hat eine Stunde?", a: ["60", "100", "24", "360"], c: 0 },
    { q: "Welche Farbe ergibt Blau + Gelb?", a: ["Grün", "Orange", "Lila", "Braun"], c: 0 },
    { q: "Wie viele Beine hat eine Spinne?", a: ["8", "6", "4", "10"], c: 0 },
    { q: "Wie viele Tage hat ein Schaltjahr?", a: ["366", "365", "364", "367"], c: 0 },
    { q: "Welche Form hat ein Stoppschild?", a: ["Achteck", "Kreis", "Dreieck", "Quadrat"], c: 0 },
    { q: "Wie viele Ecken hat ein Würfel?", a: ["8", "6", "12", "4"], c: 0 },
    { q: "Was misst man mit einem Thermometer?", a: ["Temperatur", "Gewicht", "Länge", "Zeit"], c: 0 },
    { q: "Wie viele Farben hat ein Regenbogen (klassisch)?", a: ["7", "5", "6", "8"], c: 0 },
    { q: "Welches ist das größte Tier der Welt?", a: ["Blauwal", "Elefant", "Giraffe", "Nashorn"], c: 0 },
    { q: "Wie viele Kontinente gibt es?", a: ["7", "5", "6", "8"], c: 0 },
    { q: "Wie viele Sekunden hat eine Minute?", a: ["60", "100", "30", "90"], c: 0 },
    { q: "Welches Symbol hat das Element Gold?", a: ["Au", "Go", "Ag", "Gd"], c: 0 },
    { q: "Wie viele Seiten hat ein Dreieck?", a: ["3", "4", "5", "6"], c: 0 },
    { q: "Wie viele Monate hat ein Jahr?", a: ["12", "10", "11", "13"], c: 0 },
    { q: "Welche Farbe entsteht aus Rot + Weiß?", a: ["Rosa", "Grau", "Orange", "Violett"], c: 0 },
    { q: "Wie viele Karten hat ein Poker-Kartenspiel (ohne Joker)?", a: ["52", "32", "36", "54"], c: 0 },
    { q: "Wie viele Millimeter sind ein Zentimeter?", a: ["10", "100", "5", "12"], c: 0 },
    { q: "Wie viele Stunden hat ein Tag?", a: ["24", "12", "48", "36"], c: 0 },
    { q: "Was ist das Gegenteil von „heiß\"?", a: ["Kalt", "Warm", "Nass", "Hell"], c: 0 },
    { q: "Welche Jahreszeit kommt nach dem Winter?", a: ["Frühling", "Herbst", "Sommer", "Sommeranfang"], c: 0 },
    { q: "Wie viele Wochen hat ein Jahr ungefähr?", a: ["52", "48", "60", "40"], c: 0 },
    { q: "Welche Zahl kommt nach 999?", a: ["1000", "990", "1001", "9999"], c: 0 },
    { q: "Wie viele Buchstaben hat das Alphabet (ohne Umlaute/ß)?", a: ["26", "24", "28", "30"], c: 0 },
    { q: "Wie viele Räder hat ein normales Auto?", a: ["4", "3", "6", "2"], c: 0 },
    { q: "Wie viele Nullen hat eine Million?", a: ["6", "3", "9", "12"], c: 0 },
    { q: "Welche Farbe hat der Himmel bei klarem Wetter?", a: ["Blau", "Grün", "Gelb", "Rot"], c: 0 },
    { q: "Wie viele Finger hat eine Hand?", a: ["5", "4", "6", "10"], c: 0 },
    { q: "Was ist das Gegenteil von „oben\"?", a: ["Unten", "Vorne", "Seite", "Mitte"], c: 0 },
    { q: "Wie viele Tage hat eine Woche?", a: ["7", "5", "6", "8"], c: 0 },
    { q: "Welche Farbe hat frischer Schnee?", a: ["Weiß", "Blau", "Grau", "Gelb"], c: 0 },
    { q: "Wie viele Augen hat ein Mensch normalerweise?", a: ["2", "1", "3", "4"], c: 0 },
    { q: "Welches Werkzeug schlägt einen Nagel ein?", a: ["Hammer", "Säge", "Zange", "Feile"], c: 0 },
    { q: "Welche Ampelfarbe bedeutet „Halt\"?", a: ["Rot", "Grün", "Gelb", "Blau"], c: 0 },
    { q: "Was benutzt man zum Schneiden von Papier?", a: ["Schere", "Löffel", "Gabel", "Pinsel"], c: 0 },
    { q: "Wie viele Minuten hat eine Viertelstunde?", a: ["15", "20", "25", "30"], c: 0 },
    { q: "Welche Farbe hat eine reife Zitrone?", a: ["Gelb", "Rot", "Grün", "Blau"], c: 0 },
    { q: "Wie viele Hälften ergeben ein Ganzes?", a: ["2", "3", "4", "1"], c: 0 },
    { q: "Welches Tier bellt?", a: ["Hund", "Katze", "Kuh", "Pferd"], c: 0 },
    { q: "Wie viele Tage hat der Februar (kein Schaltjahr)?", a: ["28", "30", "29", "31"], c: 0 },
    { q: "Welche Zahl ist die Hälfte von 100?", a: ["50", "25", "40", "10"], c: 0 },
    { q: "Wie viele Ecken hat ein Sechseck?", a: ["6", "5", "7", "8"], c: 0 },
    { q: "Wie viele Gramm hat ein Kilogramm?", a: ["1000", "100", "500", "10"], c: 0 },
    { q: "Welche Farbe hat Gras?", a: ["Grün", "Blau", "Braun", "Gelb"], c: 0 },
    { q: "Wie viele Räder hat ein Fahrrad?", a: ["2", "3", "4", "1"], c: 0 },
    { q: "Welches Getränk kommt von der Kuh?", a: ["Milch", "Saft", "Wein", "Tee"], c: 0 },
    { q: "Wie viele Zentimeter sind ein Meter?", a: ["100", "10", "1000", "50"], c: 0 },
    { q: "Welche Farbe entsteht aus Gelb + Rot?", a: ["Orange", "Grün", "Lila", "Grau"], c: 0 },
    { q: "Wie viele Beine hat ein Tisch üblicherweise?", a: ["4", "3", "2", "6"], c: 0 },
    { q: "Wie viele Stunden hat ein halber Tag?", a: ["12", "6", "24", "10"], c: 0 },
    { q: "Was zeigt eine Uhr an?", a: ["Die Uhrzeit", "Das Wetter", "Das Gewicht", "Die Länge"], c: 0 },
    { q: "Wie viele Beine hat ein Hocker meist?", a: ["3", "2", "5", "6"], c: 0 },
    { q: "Welche Farbe hat ein klarer Nachthimmel?", a: ["Schwarz", "Weiß", "Rot", "Grün"], c: 0 },
    { q: "Wie viele Wochentage sind ein Wochenende?", a: ["2", "1", "3", "4"], c: 0 },
    { q: "Was braucht ein Mensch zum Atmen?", a: ["Luft", "Sand", "Metall", "Papier"], c: 0 },
    { q: "Wie viele halbe Liter ergeben einen Liter?", a: ["2", "3", "4", "10"], c: 0 },
  ],
  geografie: [
    { q: "Hauptstadt von Frankreich?", a: ["Paris", "Lyon", "Marseille", "Nizza"], c: 0 },
    { q: "Hauptstadt von Italien?", a: ["Rom", "Mailand", "Venedig", "Neapel"], c: 0 },
    { q: "Hauptstadt von Japan?", a: ["Tokio", "Kyoto", "Osaka", "Peking"], c: 0 },
    { q: "Hauptstadt von Spanien?", a: ["Madrid", "Barcelona", "Sevilla", "Valencia"], c: 0 },
    { q: "Auf welchem Kontinent liegt Ägypten?", a: ["Afrika", "Asien", "Europa", "Südamerika"], c: 0 },
    { q: "Welches ist das flächengrößte Land der Erde?", a: ["Russland", "Kanada", "China", "USA"], c: 0 },
    { q: "Hauptstadt von Deutschland?", a: ["Berlin", "München", "Hamburg", "Köln"], c: 0 },
    { q: "Welcher Ozean ist der größte?", a: ["Pazifik", "Atlantik", "Indischer", "Arktischer"], c: 0 },
    { q: "In welchem Land steht der Eiffelturm?", a: ["Frankreich", "Italien", "Spanien", "Belgien"], c: 0 },
    { q: "Hauptstadt von Griechenland?", a: ["Athen", "Thessaloniki", "Sparta", "Patras"], c: 0 },
    { q: "Hauptstadt der Schweiz?", a: ["Bern", "Zürich", "Genf", "Basel"], c: 0 },
    { q: "Wie heißt der höchste Berg der Welt?", a: ["Mount Everest", "K2", "Mont Blanc", "Kilimandscharo"], c: 0 },
    { q: "Hauptstadt von Großbritannien?", a: ["London", "Manchester", "Liverpool", "Oxford"], c: 0 },
    { q: "Auf welchem Kontinent liegt Brasilien?", a: ["Südamerika", "Afrika", "Asien", "Europa"], c: 0 },
    { q: "Welches Land hat die Form eines Stiefels?", a: ["Italien", "Spanien", "Griechenland", "Portugal"], c: 0 },
    { q: "Hauptstadt der USA?", a: ["Washington, D.C.", "New York", "Los Angeles", "Chicago"], c: 0 },
    { q: "Welcher Kontinent ist der kälteste?", a: ["Antarktis", "Europa", "Asien", "Afrika"], c: 0 },
    { q: "Durch welches Land fließt der Nil hauptsächlich?", a: ["Ägypten", "Brasilien", "Indien", "China"], c: 0 },
    { q: "Auf welchem Kontinent liegt die Sahara?", a: ["Afrika", "Asien", "Australien", "Europa"], c: 0 },
    { q: "Hauptstadt von Russland?", a: ["Moskau", "Sankt Petersburg", "Kiew", "Minsk"], c: 0 },
    { q: "Hauptstadt von China?", a: ["Peking", "Shanghai", "Hongkong", "Tokio"], c: 0 },
    { q: "Hauptstadt von Portugal?", a: ["Lissabon", "Porto", "Madrid", "Faro"], c: 0 },
    { q: "Welches Meer liegt zwischen Europa und Afrika?", a: ["Mittelmeer", "Nordsee", "Ostsee", "Schwarzes Meer"], c: 0 },
    { q: "Welcher ist der längste Fluss Europas?", a: ["Wolga", "Donau", "Rhein", "Themse"], c: 0 },
    { q: "Hauptstadt der Niederlande?", a: ["Amsterdam", "Rotterdam", "Den Haag", "Utrecht"], c: 0 },
    { q: "Hauptstadt von Schweden?", a: ["Stockholm", "Göteborg", "Oslo", "Malmö"], c: 0 },
    { q: "Hauptstadt von Norwegen?", a: ["Oslo", "Bergen", "Stockholm", "Helsinki"], c: 0 },
    { q: "Hauptstadt von Polen?", a: ["Warschau", "Krakau", "Danzig", "Breslau"], c: 0 },
    { q: "Hauptstadt von Ungarn?", a: ["Budapest", "Wien", "Prag", "Bratislava"], c: 0 },
    { q: "Hauptstadt von Tschechien?", a: ["Prag", "Brünn", "Wien", "Krakau"], c: 0 },
    { q: "Hauptstadt von Belgien?", a: ["Brüssel", "Antwerpen", "Gent", "Brügge"], c: 0 },
    { q: "Hauptstadt von Kanada?", a: ["Ottawa", "Toronto", "Montreal", "Vancouver"], c: 0 },
    { q: "Hauptstadt von Australien?", a: ["Canberra", "Sydney", "Melbourne", "Perth"], c: 0 },
    { q: "Hauptstadt von Ägypten?", a: ["Kairo", "Alexandria", "Gizeh", "Luxor"], c: 0 },
    { q: "Hauptstadt von Dänemark?", a: ["Kopenhagen", "Oslo", "Stockholm", "Hamburg"], c: 0 },
    { q: "Hauptstadt von Finnland?", a: ["Helsinki", "Oslo", "Stockholm", "Tallinn"], c: 0 },
    { q: "Welches ist der kleinste Kontinent?", a: ["Australien", "Europa", "Antarktis", "Asien"], c: 0 },
    { q: "In welchem Land steht der schiefe Turm von Pisa?", a: ["Italien", "Frankreich", "Spanien", "Griechenland"], c: 0 },
    { q: "Welches Land ist bekannt für Tulpen und Windmühlen?", a: ["Niederlande", "Belgien", "Dänemark", "Schweden"], c: 0 },
    { q: "Auf welchem Kontinent liegt Indien?", a: ["Asien", "Afrika", "Europa", "Australien"], c: 0 },
    { q: "Auf welchem Kontinent liegt Kanada?", a: ["Nordamerika", "Südamerika", "Europa", "Asien"], c: 0 },
    { q: "Welche Wüste ist die größte heiße Wüste der Erde?", a: ["Sahara", "Gobi", "Kalahari", "Atacama"], c: 0 },
    { q: "Welcher Kanal verbindet Mittelmeer und Rotes Meer?", a: ["Suezkanal", "Panamakanal", "Nord-Ostsee-Kanal", "Kieler Kanal"], c: 0 },
    { q: "In welchem Land liegt die Stadt Sydney?", a: ["Australien", "Neuseeland", "USA", "Südafrika"], c: 0 },
    { q: "Welche Insel ist die größte der Welt?", a: ["Grönland", "Madagaskar", "Island", "Borneo"], c: 0 },
    { q: "Welcher Fluss fließt durch London?", a: ["Themse", "Seine", "Rhein", "Donau"], c: 0 },
    { q: "Welches Land liegt zwischen Frankreich und Portugal?", a: ["Spanien", "Italien", "Marokko", "Andorra"], c: 0 },
    { q: "Welches Land grenzt im Süden an die USA?", a: ["Mexiko", "Kanada", "Kuba", "Brasilien"], c: 0 },
    { q: "Auf welchem Kontinent liegt Kenia?", a: ["Afrika", "Asien", "Südamerika", "Australien"], c: 0 },
    { q: "Welches Gebirge trennt Europa und Asien?", a: ["Ural", "Alpen", "Anden", "Kaukasus"], c: 0 },
    { q: "Welcher Berg ist der höchste der Alpen?", a: ["Mont Blanc", "Matterhorn", "Großglockner", "Zugspitze"], c: 0 },
    { q: "In welchem Land steht die Chinesische Mauer?", a: ["China", "Japan", "Indien", "Korea"], c: 0 },
    { q: "Welches Meer liegt im Norden Deutschlands?", a: ["Nordsee", "Mittelmeer", "Schwarzes Meer", "Adria"], c: 0 },
    { q: "Hauptstadt von Türkei?", a: ["Ankara", "Istanbul", "Izmir", "Bursa"], c: 0 },
    { q: "Hauptstadt von Irland?", a: ["Dublin", "Belfast", "Cork", "Galway"], c: 0 },
  ],
  natur: [
    { q: "Welches Säugetier legt Eier?", a: ["Schnabeltier", "Delfin", "Fledermaus", "Wal"], c: 0 },
    { q: "Wie viele Beine hat ein Insekt?", a: ["6", "8", "4", "10"], c: 0 },
    { q: "Welcher Baum trägt Eicheln?", a: ["Eiche", "Birke", "Ahorn", "Buche"], c: 0 },
    { q: "Was stellen Bienen her?", a: ["Honig", "Milch", "Seide", "Butter"], c: 0 },
    { q: "Welches ist das schnellste Landtier?", a: ["Gepard", "Löwe", "Pferd", "Gazelle"], c: 0 },
    { q: "Wie nennt man ein Frosch-Baby?", a: ["Kaulquappe", "Larve", "Kitz", "Welpe"], c: 0 },
    { q: "Welches Gas atmen Menschen zum Leben ein?", a: ["Sauerstoff", "Kohlendioxid", "Stickstoff", "Helium"], c: 0 },
    { q: "Wie viele Herzen hat ein Krake?", a: ["3", "1", "2", "4"], c: 0 },
    { q: "Was frisst ein Panda hauptsächlich?", a: ["Bambus", "Fleisch", "Fisch", "Gras"], c: 0 },
    { q: "Welcher Vogel kann nicht fliegen?", a: ["Pinguin", "Adler", "Spatz", "Taube"], c: 0 },
    { q: "Wie nennt man versteinerte Überreste von Lebewesen?", a: ["Fossilien", "Mineralien", "Kristalle", "Erze"], c: 0 },
    { q: "Welches Tier hat einen besonders langen Hals?", a: ["Giraffe", "Elefant", "Nashorn", "Kamel"], c: 0 },
    { q: "Welcher Vogel kann rückwärts fliegen?", a: ["Kolibri", "Adler", "Storch", "Möwe"], c: 0 },
    { q: "Wofür ist ein Chamäleon bekannt?", a: ["Es ändert die Farbe", "Es fliegt", "Es leuchtet", "Es schwimmt sehr schnell"], c: 0 },
    { q: "Welcher Vogel gilt als besonders klug?", a: ["Rabe", "Taube", "Huhn", "Spatz"], c: 0 },
    { q: "Wie nennt man es, wenn Tiere den Winter verschlafen?", a: ["Winterschlaf", "Sommerschlaf", "Nachtschlaf", "Tiefschlaf"], c: 0 },
    { q: "Welches ist das größte lebende Reptil?", a: ["Salzwasserkrokodil", "Komodowaran", "Anakonda", "Leguan"], c: 0 },
    { q: "Welche Pflanze fängt Insekten?", a: ["Venusfliegenfalle", "Sonnenblume", "Kaktus", "Farn"], c: 0 },
    { q: "Wie viele Flügel hat eine Biene?", a: ["4", "2", "6", "8"], c: 0 },
    { q: "Was wird aus einer Raupe?", a: ["Schmetterling", "Käfer", "Fliege", "Spinne"], c: 0 },
    { q: "Welches Tier hat schwarz-weiße Streifen?", a: ["Zebra", "Giraffe", "Leopard", "Panther"], c: 0 },
    { q: "Welches Tier ist bekannt für seinen Rüssel?", a: ["Elefant", "Löwe", "Zebra", "Bär"], c: 0 },
    { q: "Was sammeln Eichhörnchen für den Winter?", a: ["Nüsse", "Fische", "Blätter", "Steine"], c: 0 },
    { q: "Welches Tier lebt in einem Bienenstock?", a: ["Biene", "Ameise", "Wespe", "Fliege"], c: 0 },
    { q: "Welches Tier wird „König der Tiere\" genannt?", a: ["Löwe", "Tiger", "Bär", "Elefant"], c: 0 },
    { q: "Welches Tier trägt einen Panzer?", a: ["Schildkröte", "Frosch", "Schlange", "Eidechse"], c: 0 },
    { q: "Welches Tier wird als „Wüstenschiff\" bezeichnet?", a: ["Kamel", "Pferd", "Esel", "Lama"], c: 0 },
    { q: "Welches Tier baut Dämme an Flüssen?", a: ["Biber", "Otter", "Fischotter", "Ratte"], c: 0 },
    { q: "Welcher Vogel ist ein Symbol für Frieden?", a: ["Taube", "Adler", "Rabe", "Eule"], c: 0 },
    { q: "Welche Blume dreht sich zur Sonne?", a: ["Sonnenblume", "Tulpe", "Rose", "Nelke"], c: 0 },
    { q: "Wie nennt man ein junges Pferd?", a: ["Fohlen", "Kalb", "Ferkel", "Küken"], c: 0 },
    { q: "Wie nennt man ein junges Rind?", a: ["Kalb", "Fohlen", "Lamm", "Ferkel"], c: 0 },
    { q: "Welches Tier hüpft und trägt sein Junges im Beutel?", a: ["Känguru", "Koala", "Affe", "Hase"], c: 0 },
    { q: "Welcher Vogel jagt nachts Mäuse?", a: ["Eule", "Spatz", "Amsel", "Storch"], c: 0 },
    { q: "Welches Tier ist das größte Landtier?", a: ["Elefant", "Nashorn", "Giraffe", "Flusspferd"], c: 0 },
    { q: "Wovon ernähren sich Schmetterlinge?", a: ["Nektar", "Fleisch", "Holz", "Gras"], c: 0 },
    { q: "Welches Tier trägt ein Geweih?", a: ["Hirsch", "Wildschwein", "Fuchs", "Wolf"], c: 0 },
    { q: "Welche Pflanze hat Stacheln und wächst in der Wüste?", a: ["Kaktus", "Farn", "Moos", "Efeu"], c: 0 },
    { q: "Welcher Baum bleibt im Winter grün?", a: ["Tanne", "Eiche", "Birke", "Ahorn"], c: 0 },
    { q: "Welches Tier legt die größten Eier?", a: ["Strauß", "Huhn", "Ente", "Gans"], c: 0 },
    { q: "Welches Meerestier hat acht Arme?", a: ["Krake", "Seestern", "Qualle", "Hai"], c: 0 },
    { q: "Welches Tier ist bekannt für sein gutes Gedächtnis?", a: ["Elefant", "Huhn", "Schaf", "Ziege"], c: 0 },
    { q: "Welches Tier lebt im Wasser und ist ein Säugetier?", a: ["Delfin", "Hai", "Thunfisch", "Krokodil"], c: 0 },
    { q: "Welches Raubtier lebt in der Arktis?", a: ["Eisbär", "Löwe", "Tiger", "Panther"], c: 0 },
    { q: "Welche Tiere leben typischerweise in einem Rudel?", a: ["Wölfe", "Katzen", "Igel", "Schildkröten"], c: 0 },
    { q: "Welches Insekt kann besonders weit springen?", a: ["Floh", "Ameise", "Fliege", "Mücke"], c: 0 },
    { q: "Welcher Fisch hat viele scharfe Zähne und ist gefürchtet?", a: ["Hai", "Karpfen", "Forelle", "Hering"], c: 0 },
    { q: "Wie nennt man Tiere, die nachts aktiv sind?", a: ["nachtaktiv", "tagaktiv", "winterfest", "wasserscheu"], c: 0 },
    { q: "Welches Tier ist für seine schwarz-weißen Streifen bekannt und lebt in Afrika?", a: ["Zebra", "Panda", "Pinguin", "Dalmatiner"], c: 0 },
    { q: "Welche Farbe hat ein typischer Marienkäfer?", a: ["Rot", "Blau", "Grün", "Gelb"], c: 0 },
    { q: "Welches Tier lebt im Meer und leuchtet manchmal?", a: ["Qualle", "Hai", "Delfin", "Wal"], c: 0 },
    { q: "Welcher Teil des Baumes ist unter der Erde?", a: ["Wurzel", "Krone", "Blüte", "Ast"], c: 0 },
    { q: "Welches Tier ist bekannt für seinen langen Rüssel und große Ohren?", a: ["Elefant", "Nashorn", "Tapir", "Büffel"], c: 0 },
    { q: "Welche Blume gilt als Symbol der Liebe?", a: ["Rose", "Löwenzahn", "Distel", "Farn"], c: 0 },
  ],
  wissenschaft: [
    { q: "Welcher Planet ist der Sonne am nächsten?", a: ["Merkur", "Venus", "Erde", "Mars"], c: 0 },
    { q: "Welches Element hat das Symbol O?", a: ["Sauerstoff", "Gold", "Osmium", "Wasserstoff"], c: 0 },
    { q: "Wie viele Planeten hat unser Sonnensystem?", a: ["8", "9", "7", "10"], c: 0 },
    { q: "Was ist H₂O?", a: ["Wasser", "Salz", "Zucker", "Luft"], c: 0 },
    { q: "Wer entwickelte die Relativitätstheorie?", a: ["Einstein", "Newton", "Darwin", "Tesla"], c: 0 },
    { q: "Welcher Planet heißt „der rote Planet\"?", a: ["Mars", "Jupiter", "Venus", "Saturn"], c: 0 },
    { q: "Welches Material zieht ein Magnet an?", a: ["Eisen", "Holz", "Glas", "Plastik"], c: 0 },
    { q: "Welches Organ pumpt das Blut?", a: ["Herz", "Lunge", "Leber", "Niere"], c: 0 },
    { q: "Woraus besteht die Sonne hauptsächlich?", a: ["Wasserstoff", "Sauerstoff", "Eisen", "Gestein"], c: 0 },
    { q: "Was entsteht, wenn Wasser gefriert?", a: ["Eis", "Dampf", "Nebel", "Rauch"], c: 0 },
    { q: "Wie nennt man Tiere, die Fleisch fressen?", a: ["Fleischfresser", "Pflanzenfresser", "Allesfresser", "Aasfresser"], c: 0 },
    { q: "Wie schnell ist ungefähr das Licht?", a: ["300.000 km/s", "300 km/s", "3.000 km/s", "30 km/s"], c: 0 },
    { q: "Wie viele Zähne hat ein erwachsener Mensch normalerweise?", a: ["32", "28", "30", "36"], c: 0 },
    { q: "Welches dieser Tiere ist ein Wirbeltier?", a: ["Hund", "Qualle", "Regenwurm", "Krake"], c: 0 },
    { q: "Was misst die Einheit „Volt\"?", a: ["Spannung", "Gewicht", "Temperatur", "Zeit"], c: 0 },
    { q: "Welcher Teil der Pflanze nimmt Wasser aus dem Boden auf?", a: ["Wurzel", "Blüte", "Blatt", "Frucht"], c: 0 },
    { q: "Welcher Planet hat auffällige Ringe?", a: ["Saturn", "Merkur", "Venus", "Mars"], c: 0 },
    { q: "Welches Gas ist am häufigsten in der Luft?", a: ["Stickstoff", "Sauerstoff", "Kohlendioxid", "Helium"], c: 0 },
    { q: "Wie nennt man Wasser in gasförmigem Zustand?", a: ["Wasserdampf", "Eis", "Nebel", "Schnee"], c: 0 },
    { q: "Was misst ein Seismograph?", a: ["Erdbeben", "Temperatur", "Wind", "Regen"], c: 0 },
    { q: "Wie viele Knochen hat ein erwachsener Mensch ungefähr?", a: ["206", "150", "300", "500"], c: 0 },
    { q: "Welche Kraft hält uns auf dem Boden?", a: ["Schwerkraft", "Magnetismus", "Reibung", "Auftrieb"], c: 0 },
    { q: "Was passiert mit den meisten Metallen bei Hitze?", a: ["Sie dehnen sich aus", "Sie schrumpfen", "Sie werden leichter", "Sie verschwinden"], c: 0 },
    { q: "Welches Organ produziert Insulin?", a: ["Bauchspeicheldrüse", "Leber", "Herz", "Niere"], c: 0 },
    { q: "Welche Kraft lässt Dinge zu Boden fallen?", a: ["Schwerkraft", "Reibung", "Magnetismus", "Auftrieb"], c: 0 },
    { q: "Welches Organ steuert das Denken?", a: ["Gehirn", "Herz", "Magen", "Lunge"], c: 0 },
    { q: "Wie lange braucht die Erde für eine Runde um die Sonne?", a: ["1 Jahr", "1 Tag", "1 Monat", "1 Woche"], c: 0 },
    { q: "Welches Gas lässt Luftballons steigen?", a: ["Helium", "Sauerstoff", "Kohlendioxid", "Stickstoff"], c: 0 },
    { q: "Wie nennt man die Lehre von den Lebewesen?", a: ["Biologie", "Geologie", "Chemie", "Physik"], c: 0 },
    { q: "Wie nennt man die Lehre von den Sternen?", a: ["Astronomie", "Astrologie", "Geografie", "Meteorologie"], c: 0 },
    { q: "Was bewegt sich schneller: Schall oder Licht?", a: ["Licht", "Schall", "Beide gleich", "Kommt drauf an"], c: 0 },
    { q: "Was zeigt ein Kompass an?", a: ["Die Himmelsrichtung", "Die Uhrzeit", "Die Temperatur", "Den Luftdruck"], c: 0 },
    { q: "Welcher Himmelskörper umkreist die Erde?", a: ["Mond", "Sonne", "Mars", "Venus"], c: 0 },
    { q: "Wie nennt man gefrorenen Regen?", a: ["Hagel", "Nebel", "Tau", "Rauch"], c: 0 },
    { q: "Was misst man in Grad Celsius?", a: ["Temperatur", "Gewicht", "Länge", "Zeit"], c: 0 },
    { q: "Wie nennt man Wasser, das vom Himmel fällt?", a: ["Regen", "Dampf", "Eis", "Wind"], c: 0 },
    { q: "Welche Wissenschaft beschäftigt sich mit Zahlen?", a: ["Mathematik", "Biologie", "Geschichte", "Musik"], c: 0 },
    { q: "Was bildet sich am Himmel aus Wassertröpfchen?", a: ["Wolken", "Sterne", "Blitze", "Regenbögen"], c: 0 },
    { q: "Was passiert mit Wasser bei 100 Grad Celsius?", a: ["Es kocht", "Es gefriert", "Es wird fest", "Nichts"], c: 0 },
    { q: "Welcher Sinn nimmt Gerüche wahr?", a: ["Geruchssinn", "Gehör", "Tastsinn", "Sehsinn"], c: 0 },
    { q: "Welches Instrument vergrößert winzige Dinge?", a: ["Mikroskop", "Teleskop", "Fernglas", "Lupe"], c: 0 },
    { q: "Wie nennt man ein Lebewesen aus nur einer Zelle?", a: ["Einzeller", "Säugetier", "Insekt", "Wirbeltier"], c: 0 },
    { q: "Welche Blutzellen transportieren Sauerstoff?", a: ["Rote Blutkörperchen", "Weiße Blutkörperchen", "Blutplättchen", "Nervenzellen"], c: 0 },
    { q: "Was atmen Pflanzen zum Wachsen ein?", a: ["Kohlendioxid", "Sauerstoff", "Stickstoff", "Helium"], c: 0 },
    { q: "Welche Energiequelle kommt von der Sonne?", a: ["Sonnenenergie", "Kohle", "Erdöl", "Erdgas"], c: 0 },
    { q: "Wie viele Zustände hat Wasser (fest, flüssig, gasförmig)?", a: ["3", "2", "4", "5"], c: 0 },
    { q: "Wie heißt der Stern im Mittelpunkt unseres Sonnensystems?", a: ["Sonne", "Mond", "Polarstern", "Sirius"], c: 0 },
    { q: "Welches Gerät zeigt den Luftdruck an?", a: ["Barometer", "Thermometer", "Kompass", "Waage"], c: 0 },
    { q: "Wie nennt man das Verglühen eines Meteors am Himmel?", a: ["Sternschnuppe", "Komet", "Nordlicht", "Blitz"], c: 0 },
    { q: "Welcher Planet ist von einem großen Sturm (roter Fleck) bekannt?", a: ["Jupiter", "Mars", "Venus", "Merkur"], c: 0 },
    { q: "Welche Farbe hat Blut mit viel Sauerstoff?", a: ["Rot", "Blau", "Grün", "Gelb"], c: 0 },
    { q: "Was leitet Strom besonders gut?", a: ["Metall", "Holz", "Gummi", "Glas"], c: 0 },
    { q: "Wie nennt man den Wechsel von Ebbe und Flut?", a: ["Gezeiten", "Strömung", "Wellen", "Brandung"], c: 0 },
  ],
  geschichte: [
    { q: "Wer war der erste Mensch am Mond?", a: ["Neil Armstrong", "Buzz Aldrin", "Juri Gagarin", "Michael Collins"], c: 0 },
    { q: "In welchem Jahr fiel die Berliner Mauer?", a: ["1989", "1961", "1991", "1979"], c: 0 },
    { q: "Welches Volk baute die Pyramiden von Gizeh?", a: ["Ägypter", "Römer", "Griechen", "Maya"], c: 0 },
    { q: "Wer schrieb „Hamlet\"?", a: ["Shakespeare", "Goethe", "Mozart", "Dante"], c: 0 },
    { q: "Wie hieß das Schiff, das 1912 sank?", a: ["Titanic", "Lusitania", "Bismarck", "Mayflower"], c: 0 },
    { q: "Welches Reich baute das Kolosseum?", a: ["Römisches Reich", "Griechenland", "Ägypten", "Osmanen"], c: 0 },
    { q: "Wann begann der Erste Weltkrieg?", a: ["1914", "1918", "1939", "1905"], c: 0 },
    { q: "Welche war eine berühmte ägyptische Königin?", a: ["Kleopatra", "Viktoria", "Elisabeth", "Maria Theresia"], c: 0 },
    { q: "Welches Land schenkte den USA die Freiheitsstatue?", a: ["Frankreich", "England", "Spanien", "Italien"], c: 0 },
    { q: "Wer erreichte 1492 Amerika?", a: ["Kolumbus", "Magellan", "Marco Polo", "Vasco da Gama"], c: 0 },
    { q: "Welches Bauwerk steht in China?", a: ["Chinesische Mauer", "Kolosseum", "Taj Mahal", "Big Ben"], c: 0 },
    { q: "Womit schrieb man im Mittelalter oft?", a: ["Gänsefeder", "Kugelschreiber", "Bleistift", "Füller"], c: 0 },
    { q: "In welchem Jahr endete der Zweite Weltkrieg?", a: ["1945", "1939", "1918", "1950"], c: 0 },
    { q: "Wer war ein berühmter französischer Kaiser?", a: ["Napoleon", "Ludwig XIV.", "Karl der Große", "de Gaulle"], c: 0 },
    { q: "Welche antike Stadt wurde vom Vesuv verschüttet?", a: ["Pompeji", "Troja", "Karthago", "Sparta"], c: 0 },
    { q: "Wer malte die Decke der Sixtinischen Kapelle?", a: ["Michelangelo", "da Vinci", "Raffael", "Botticelli"], c: 0 },
    { q: "Wer entdeckte laut Legende die Schwerkraft durch einen Apfel?", a: ["Newton", "Einstein", "Galilei", "Kepler"], c: 0 },
    { q: "In welchem Land entstand die Olympische Idee (Antike)?", a: ["Griechenland", "Italien", "Ägypten", "Türkei"], c: 0 },
    { q: "Wer schrieb „Faust\"?", a: ["Goethe", "Schiller", "Kafka", "Mann"], c: 0 },
    { q: "Welche Schrift benutzten die alten Ägypter?", a: ["Hieroglyphen", "Runen", "Keilschrift", "Latein"], c: 0 },
    { q: "Wer war der erste Präsident der USA?", a: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"], c: 0 },
    { q: "Wer erfand den Buchdruck mit beweglichen Lettern in Europa?", a: ["Gutenberg", "Newton", "Edison", "Galilei"], c: 0 },
    { q: "Welche Epoche folgte auf das Mittelalter?", a: ["Renaissance", "Antike", "Steinzeit", "Barock"], c: 0 },
    { q: "Wie hieß der Seefahrer, der als Erster die Welt umsegelte?", a: ["Magellan", "Kolumbus", "Marco Polo", "Vasco da Gama"], c: 0 },
    { q: "Welche Zivilisation baute Machu Picchu?", a: ["Inka", "Maya", "Azteken", "Ägypter"], c: 0 },
    { q: "Welche Zivilisation baute Stufenpyramiden in Mittelamerika?", a: ["Maya", "Römer", "Wikinger", "Griechen"], c: 0 },
    { q: "In welchem Jahr landete der erste Mensch auf dem Mond?", a: ["1969", "1959", "1979", "1985"], c: 0 },
    { q: "Welche Königin regierte England sehr lange im 19. Jahrhundert?", a: ["Victoria", "Elisabeth I.", "Maria Stuart", "Anne"], c: 0 },
    { q: "Welche Stadt gilt als Wiege der Demokratie in der Antike?", a: ["Athen", "Rom", "Sparta", "Theben"], c: 0 },
    { q: "Wer hielt die berühmte Rede „I have a dream\"?", a: ["Martin Luther King", "John F. Kennedy", "Nelson Mandela", "Barack Obama"], c: 0 },
    { q: "In welchem Jahrhundert fand die Französische Revolution statt?", a: ["18. Jahrhundert", "17. Jahrhundert", "19. Jahrhundert", "16. Jahrhundert"], c: 0 },
    { q: "Wer entwickelte die Evolutionstheorie?", a: ["Darwin", "Newton", "Mendel", "Pasteur"], c: 0 },
    { q: "Wie hieß der Gegenspieler der USA im Kalten Krieg?", a: ["Sowjetunion", "China", "Japan", "Deutschland"], c: 0 },
    { q: "Wer war ein berühmter Feldherr aus Makedonien in der Antike?", a: ["Alexander der Große", "Cäsar", "Hannibal", "Napoleon"], c: 0 },
    { q: "In welchem Land begann die Industrielle Revolution?", a: ["Großbritannien", "Frankreich", "USA", "Deutschland"], c: 0 },
    { q: "Welche Erfindung von Edison beleuchtet Räume?", a: ["Glühbirne", "Telefon", "Radio", "Dampfmaschine"], c: 0 },
    { q: "Wer entdeckte das Penicillin?", a: ["Alexander Fleming", "Louis Pasteur", "Robert Koch", "Marie Curie"], c: 0 },
    { q: "Welche Kaiserin von Österreich wird „Sisi\" genannt?", a: ["Elisabeth", "Maria Theresia", "Viktoria", "Katharina"], c: 0 },
    { q: "In welchem Land regierten einst die Pharaonen?", a: ["Ägypten", "Griechenland", "Persien", "Rom"], c: 0 },
    { q: "Welches Schiff brachte 1620 Pilger nach Amerika?", a: ["Mayflower", "Titanic", "Santa Maria", "Beagle"], c: 0 },
    { q: "Wer war ein berühmter Universalgelehrter der Renaissance (Maler & Erfinder)?", a: ["Leonardo da Vinci", "Michelangelo", "Raffael", "Donatello"], c: 0 },
    { q: "Welche antike Hauptstadt war Zentrum eines riesigen Weltreichs (Kolosseum)?", a: ["Rom", "Athen", "Kairo", "Babylon"], c: 0 },
    { q: "Wie reisten Menschen vor der Eisenbahn über Land?", a: ["Pferdekutsche", "Auto", "Flugzeug", "U-Bahn"], c: 0 },
    { q: "Welche Waffe war typisch für mittelalterliche Ritter?", a: ["Schwert", "Gewehr", "Pistole", "Bogen aus Metall"], c: 0 },
    { q: "Welches Volk war für seine Langschiffe und Runen bekannt?", a: ["Wikinger", "Römer", "Griechen", "Ägypter"], c: 0 },
    { q: "Welcher Forscher formulierte die drei Bewegungsgesetze?", a: ["Newton", "Einstein", "Galilei", "Kopernikus"], c: 0 },
    { q: "In welchem Jahr begann der Zweite Weltkrieg?", a: ["1939", "1914", "1945", "1929"], c: 0 },
    { q: "Welcher Entdecker segelte 1492 im Auftrag Spaniens nach Westen?", a: ["Kolumbus", "Magellan", "Cook", "Drake"], c: 0 },
    { q: "Welches antike Weltwunder in Ägypten existiert noch heute?", a: ["Pyramiden von Gizeh", "Koloss von Rhodos", "Leuchtturm von Alexandria", "Hängende Gärten"], c: 0 },
  ],
  sport: [
    { q: "Wie viele Fußballspieler stehen pro Team am Feld?", a: ["11", "9", "10", "12"], c: 0 },
    { q: "In welchem Sport gibt es einen „Slam Dunk\"?", a: ["Basketball", "Tennis", "Fußball", "Golf"], c: 0 },
    { q: "Wie viele Ringe hat das olympische Symbol?", a: ["5", "4", "6", "3"], c: 0 },
    { q: "In welchem Sport ist Lionel Messi berühmt?", a: ["Fußball", "Basketball", "Tennis", "Formel 1"], c: 0 },
    { q: "Wie lang ist ein Marathon ungefähr?", a: ["42 km", "21 km", "10 km", "100 km"], c: 0 },
    { q: "Welcher Sport wird in Wimbledon gespielt?", a: ["Tennis", "Golf", "Cricket", "Rugby"], c: 0 },
    { q: "Womit wird beim Eishockey gespielt?", a: ["Puck", "Ball", "Feder", "Ring"], c: 0 },
    { q: "In welchem Sport gibt es einen „Strike\"?", a: ["Bowling", "Fußball", "Schwimmen", "Reiten"], c: 0 },
    { q: "Wie viele Basketballspieler stehen pro Team am Feld?", a: ["5", "6", "7", "4"], c: 0 },
    { q: "Wie sieht die Zielflagge im Motorsport aus?", a: ["Schwarz-weiß kariert", "Rot", "Grün", "Blau"], c: 0 },
    { q: "Wie oft finden die Olympischen Sommerspiele statt?", a: ["Alle 4 Jahre", "Jedes Jahr", "Alle 2 Jahre", "Alle 5 Jahre"], c: 0 },
    { q: "Was ruft man beim Golf zur Warnung?", a: ["Fore", "Out", "Fault", "Time"], c: 0 },
    { q: "Wie viele Löcher hat eine Standard-Golfrunde?", a: ["18", "9", "12", "24"], c: 0 },
    { q: "In welchem Land ist Sumo-Ringen zu Hause?", a: ["Japan", "China", "Korea", "Thailand"], c: 0 },
    { q: "Wie viele Punkte bringt ein Touchdown im American Football?", a: ["6", "3", "7", "2"], c: 0 },
    { q: "Welche Sportart spielt man mit Schläger und Federball?", a: ["Badminton", "Tennis", "Squash", "Tischtennis"], c: 0 },
    { q: "Wie viele Volleyballspieler stehen pro Team am Feld?", a: ["6", "5", "7", "11"], c: 0 },
    { q: "In welchem Sport ist Roger Federer eine Legende?", a: ["Tennis", "Golf", "Ski", "Boxen"], c: 0 },
    { q: "Wie lange dauert ein Fußballspiel regulär?", a: ["90 Minuten", "60 Minuten", "120 Minuten", "45 Minuten"], c: 0 },
    { q: "Welcher Sport wird auf Eis mit Besen gespielt?", a: ["Curling", "Eishockey", "Eiskunstlauf", "Bob"], c: 0 },
    { q: "In welchem Land wird die Tour de France gefahren?", a: ["Frankreich", "Italien", "Spanien", "Belgien"], c: 0 },
    { q: "Womit spielt man Basketball?", a: ["Ball", "Puck", "Schläger", "Federball"], c: 0 },
    { q: "Wie viele Minuten dauert eine Halbzeit im Fußball?", a: ["45", "30", "60", "40"], c: 0 },
    { q: "In welchem Sport gibt es einen „Homerun\"?", a: ["Baseball", "Fußball", "Tennis", "Golf"], c: 0 },
    { q: "Welche Sportart macht Usain Bolt berühmt?", a: ["Sprint", "Weitsprung", "Marathon", "Hochsprung"], c: 0 },
    { q: "Wie heißt die höchste Fußballliga in England?", a: ["Premier League", "Bundesliga", "Serie A", "La Liga"], c: 0 },
    { q: "Wie viele Spieler hat eine Handball-Mannschaft am Feld?", a: ["7", "6", "5", "11"], c: 0 },
    { q: "Welche Sportart betreibt man im Wasser über mehrere Bahnen?", a: ["Schwimmen", "Rudern", "Segeln", "Tauchen"], c: 0 },
    { q: "Welche Sportart wird auf einem Ring mit Handschuhen ausgetragen?", a: ["Boxen", "Fechten", "Judo", "Karate"], c: 0 },
    { q: "In welchem Land wurde Fußball erfunden?", a: ["England", "Brasilien", "Italien", "Deutschland"], c: 0 },
    { q: "Welche Sportart betreibt man mit Pfeilen auf eine Scheibe?", a: ["Dart", "Bogenschießen", "Billard", "Curling"], c: 0 },
    { q: "Welcher Sport nutzt Pferde und Sprünge über Hindernisse?", a: ["Springreiten", "Polo", "Trabrennen", "Voltigieren"], c: 0 },
    { q: "Wie nennt man das Tor beim Basketball?", a: ["Korb", "Netz", "Kasten", "Loch"], c: 0 },
    { q: "Welche Sportart kombiniert Schwimmen, Radfahren und Laufen?", a: ["Triathlon", "Zehnkampf", "Pentathlon", "Duathlon"], c: 0 },
    { q: "Welches Land gewann die Fußball-WM 2014?", a: ["Deutschland", "Brasilien", "Argentinien", "Spanien"], c: 0 },
    { q: "Wie nennt man drei Tore eines Spielers in einem Spiel?", a: ["Hattrick", "Doppelpack", "Triple", "Dreisatz"], c: 0 },
    { q: "Welche Sportart betreibt man auf einer Half-Pipe im Schnee?", a: ["Snowboarden", "Skispringen", "Rodeln", "Eislaufen"], c: 0 },
    { q: "Wie viele Spieler hat eine Baseball-Mannschaft am Feld?", a: ["9", "7", "11", "5"], c: 0 },
    { q: "Wie heißt der wichtigste Radsport-Wettkampf in Frankreich?", a: ["Tour de France", "Giro d'Italia", "Vuelta", "Paris-Roubaix"], c: 0 },
    { q: "Wie oft findet die Fußball-Weltmeisterschaft statt?", a: ["Alle 4 Jahre", "Jedes Jahr", "Alle 2 Jahre", "Alle 3 Jahre"], c: 0 },
    { q: "Wie viele Punkte zählt ein normaler Korb aus dem Spiel im Basketball?", a: ["2", "1", "3", "5"], c: 0 },
    { q: "Welche Sportart fährt man auf einer Piste im Winter mit zwei Brettern?", a: ["Skifahren", "Rodeln", "Eishockey", "Curling"], c: 0 },
    { q: "Wie nennt man einen perfekten Wurf beim Tennis, den der Gegner nicht erreicht?", a: ["Ass", "Tor", "Strike", "Birdie"], c: 0 },
    { q: "In welcher Stadt findet das berühmte Formel-1-Rennen mit engen Straßen statt?", a: ["Monaco", "Berlin", "Wien", "Madrid"], c: 0 },
    { q: "Welche Sportart hat Michael Jordan berühmt gemacht?", a: ["Basketball", "Baseball", "Football", "Golf"], c: 0 },
    { q: "Wie viele Runden hat ein Profi-Boxkampf um den Titel maximal?", a: ["12", "10", "15", "8"], c: 0 },
    { q: "Wie heißt ein guter Golfschlag, ein Schlag unter Par?", a: ["Birdie", "Ass", "Strike", "Homerun"], c: 0 },
    { q: "Welche Sportart wird mit einem kleinen weißen Ball auf einem Tisch gespielt?", a: ["Tischtennis", "Squash", "Billard", "Federball"], c: 0 },
    { q: "In welchem Land finden die Fußballklubs Real Madrid und Barcelona ihr Zuhause?", a: ["Spanien", "Italien", "Portugal", "Frankreich"], c: 0 },
    { q: "Wie heißt der Sprung ins Wasser vom hohen Turm als Sportart?", a: ["Turmspringen", "Synchronschwimmen", "Wasserball", "Rudern"], c: 0 },
    { q: "Welche Trophäe erhält der Sieger der Fußball-Weltmeisterschaft?", a: ["WM-Pokal", "Goldener Schuh", "Champions-Cup", "Davis Cup"], c: 0 },
  ],
  kultur: [
    { q: "Wer komponierte die „Kleine Nachtmusik\"?", a: ["Mozart", "Beethoven", "Bach", "Haydn"], c: 0 },
    { q: "Wie heißt der Zauberschüler aus J. K. Rowlings Büchern?", a: ["Harry Potter", "Frodo", "Percy", "Bilbo"], c: 0 },
    { q: "Welches Instrument hat 88 Tasten?", a: ["Klavier", "Gitarre", "Geige", "Harfe"], c: 0 },
    { q: "Wer malte die „Mona Lisa\"?", a: ["Leonardo da Vinci", "Picasso", "Van Gogh", "Michelangelo"], c: 0 },
    { q: "Wie viele Saiten hat eine klassische Gitarre?", a: ["6", "4", "5", "7"], c: 0 },
    { q: "In welchem Film heißt es „Möge die Macht mit dir sein\"?", a: ["Star Wars", "Star Trek", "Herr der Ringe", "Avatar"], c: 0 },
    { q: "Welche Band sang „Hey Jude\"?", a: ["The Beatles", "Rolling Stones", "Queen", "ABBA"], c: 0 },
    { q: "Wer schrieb das Theaterstück „Die Räuber\"?", a: ["Schiller", "Goethe", "Lessing", "Brecht"], c: 0 },
    { q: "Wie heißt Micky Maus' Hund?", a: ["Pluto", "Goofy", "Rex", "Bello"], c: 0 },
    { q: "Welches ist ein Blechblasinstrument?", a: ["Trompete", "Geige", "Klavier", "Flöte"], c: 0 },
    { q: "Aus welchem Land kommt die Band ABBA?", a: ["Schweden", "Norwegen", "England", "USA"], c: 0 },
    { q: "Wer schrieb „Romeo und Julia\"?", a: ["Shakespeare", "Goethe", "Molière", "Ibsen"], c: 0 },
    { q: "Wer komponierte die „Zauberflöte\"?", a: ["Mozart", "Verdi", "Wagner", "Bach"], c: 0 },
    { q: "Welche Kunstrichtung hat Picasso mitbegründet?", a: ["Kubismus", "Impressionismus", "Barock", "Renaissance"], c: 0 },
    { q: "Aus wie vielen Musikern bestand der Kern der Beatles?", a: ["4", "3", "5", "2"], c: 0 },
    { q: "Welches Instrument spielt man mit einem Bogen?", a: ["Geige", "Flöte", "Trompete", "Klavier"], c: 0 },
    { q: "Wer schrieb das Märchen „Die kleine Meerjungfrau\"?", a: ["Hans Christian Andersen", "Gebrüder Grimm", "Äsop", "Charles Perrault"], c: 0 },
    { q: "In welcher Stadt liegt das berühmte Broadway-Theaterviertel?", a: ["New York", "London", "Paris", "Los Angeles"], c: 0 },
    { q: "Welche Farbe entsteht beim Malen aus Rot und Blau?", a: ["Violett", "Grün", "Orange", "Braun"], c: 0 },
    { q: "Wer komponierte die 9. Sinfonie mit der „Ode an die Freude\"?", a: ["Beethoven", "Mozart", "Brahms", "Schubert"], c: 0 },
    { q: "Wer schrieb die Märchen „Hänsel und Gretel\"?", a: ["Gebrüder Grimm", "Hans Christian Andersen", "Wilhelm Busch", "Astrid Lindgren"], c: 0 },
    { q: "Welche Band sang „Bohemian Rhapsody\"?", a: ["Queen", "The Beatles", "ABBA", "Rolling Stones"], c: 0 },
    { q: "Wer malte „Die Sternennacht\"?", a: ["Van Gogh", "Picasso", "Monet", "Dalí"], c: 0 },
    { q: "Welches Musikgenre stammt aus Jamaika?", a: ["Reggae", "Jazz", "Tango", "Flamenco"], c: 0 },
    { q: "Wie heißt der Detektiv von Arthur Conan Doyle?", a: ["Sherlock Holmes", "Hercule Poirot", "Miss Marple", "Kommissar Maigret"], c: 0 },
    { q: "Wer schrieb „Die Verwandlung\"?", a: ["Franz Kafka", "Thomas Mann", "Goethe", "Hermann Hesse"], c: 0 },
    { q: "Aus welchem Land stammt der Tango?", a: ["Argentinien", "Spanien", "Brasilien", "Mexiko"], c: 0 },
    { q: "Aus welchem Land stammt der Flamenco?", a: ["Spanien", "Italien", "Portugal", "Frankreich"], c: 0 },
    { q: "Wer schrieb „Der kleine Prinz\"?", a: ["Antoine de Saint-Exupéry", "Jules Verne", "Victor Hugo", "Molière"], c: 0 },
    { q: "Welcher Künstler ist für seine Suppendosen-Bilder bekannt?", a: ["Andy Warhol", "Salvador Dalí", "Pablo Picasso", "Jackson Pollock"], c: 0 },
    { q: "Wer schrieb „Krieg und Frieden\"?", a: ["Tolstoi", "Dostojewski", "Tschechow", "Puschkin"], c: 0 },
    { q: "Welcher Komponist war am Ende seines Lebens taub?", a: ["Beethoven", "Mozart", "Bach", "Chopin"], c: 0 },
    { q: "Welcher Maler ist für seine Seerosen-Bilder bekannt?", a: ["Claude Monet", "Rembrandt", "Vermeer", "Rubens"], c: 0 },
    { q: "Welche Musikrichtung entstand in New Orleans?", a: ["Jazz", "Reggae", "Techno", "Country"], c: 0 },
    { q: "Wer schuf die berühmte Marmor-Skulptur „David\"?", a: ["Michelangelo", "Leonardo da Vinci", "Rodin", "Bernini"], c: 0 },
    { q: "Wer schrieb die Krimis um Miss Marple?", a: ["Agatha Christie", "Arthur Conan Doyle", "Edgar Allan Poe", "Georges Simenon"], c: 0 },
    { q: "Welcher Roman handelt von der Jagd nach einem weißen Wal?", a: ["Moby Dick", "Der alte Mann und das Meer", "Robinson Crusoe", "20.000 Meilen unter dem Meer"], c: 0 },
    { q: "Welche Kunstepoche prägte prunkvolle Kirchen im 17. Jahrhundert?", a: ["Barock", "Gotik", "Renaissance", "Klassik"], c: 0 },
    { q: "Wer komponierte das Ballett „Der Nussknacker\"?", a: ["Tschaikowski", "Strawinsky", "Prokofjew", "Debussy"], c: 0 },
    { q: "Wer erfand die Figur „Pippi Langstrumpf\"?", a: ["Astrid Lindgren", "Erich Kästner", "Michael Ende", "Otfried Preußler"], c: 0 },
    { q: "Welches Instrument spielt man in Kirchen mit Tasten und Pfeifen?", a: ["Orgel", "Klavier", "Cembalo", "Akkordeon"], c: 0 },
    { q: "Welche Oper von Bizet handelt von einer Zigeunerin und einem Stierkämpfer?", a: ["Carmen", "Aida", "Tosca", "La Traviata"], c: 0 },
    { q: "Welche Farbe symbolisiert in Europa traditionell Trauer?", a: ["Schwarz", "Weiß", "Rot", "Grün"], c: 0 },
    { q: "In welchem Land entstand die Oper als Kunstform ursprünglich?", a: ["Italien", "Deutschland", "Frankreich", "Österreich"], c: 0 },
    { q: "Welches große Streichinstrument ist das tiefste im Orchester?", a: ["Kontrabass", "Cello", "Bratsche", "Geige"], c: 0 },
    { q: "Welcher Roman spielt in Verona und handelt von zwei Liebenden?", a: ["Romeo und Julia", "Faust", "Hamlet", "Othello"], c: 0 },
    { q: "Welcher Maler gilt als Mitbegründer des Kubismus?", a: ["Picasso", "Monet", "Rembrandt", "Michelangelo"], c: 0 },
    { q: "Welches Wandbild von Leonardo da Vinci zeigt Jesus mit seinen Jüngern?", a: ["Das Abendmahl", "Die Erschaffung Adams", "Die Nachtwache", "Der Schrei"], c: 0 },
    { q: "Welche Band aus England sang „Satisfaction\"?", a: ["Rolling Stones", "Beatles", "Queen", "The Who"], c: 0 },
  ],
  oesterreich: [
    { q: "Was ist die Hauptstadt von Österreich?", a: ["Wien", "Graz", "Linz", "Salzburg"], c: 0 },
    { q: "Welcher Fluss fließt durch Wien?", a: ["Donau", "Inn", "Salzach", "Mur"], c: 0 },
    { q: "Wie heißt der höchste Berg Österreichs?", a: ["Großglockner", "Wildspitze", "Dachstein", "Watzmann"], c: 0 },
    { q: "Welche Mehlspeise ist typisch österreichisch?", a: ["Sachertorte", "Schwarzwälder", "Tiramisu", "Baklava"], c: 0 },
    { q: "Wie viele Bundesländer hat Österreich?", a: ["9", "8", "10", "7"], c: 0 },
    { q: "Welcher Komponist wurde in Salzburg geboren?", a: ["Mozart", "Beethoven", "Strauß", "Haydn"], c: 0 },
    { q: "Wie heißt Österreichs Währung heute?", a: ["Euro", "Schilling", "Krone", "Franken"], c: 0 },
    { q: "Welches Tier ist im österreichischen Wappen?", a: ["Adler", "Löwe", "Bär", "Pferd"], c: 0 },
    { q: "Welcher See liegt im Salzkammergut?", a: ["Wolfgangsee", "Bodensee", "Gardasee", "Genfersee"], c: 0 },
    { q: "Wie heißt der Wiener Vergnügungspark mit dem Riesenrad?", a: ["Prater", "Oktoberfest", "Disneyland", "Europapark"], c: 0 },
    { q: "Welche Farben hat die österreichische Flagge?", a: ["Rot-Weiß-Rot", "Schwarz-Rot-Gold", "Blau-Weiß", "Rot-Weiß-Grün"], c: 0 },
    { q: "In welchem Bundesland liegt die Stadt Innsbruck?", a: ["Tirol", "Salzburg", "Kärnten", "Vorarlberg"], c: 0 },
    { q: "Welcher berühmte Donau-Walzer stammt von Johann Strauß?", a: ["An der schönen blauen Donau", "Für Elise", "Türkischer Marsch", "Bolero"], c: 0 },
    { q: "Welches ist das flächengrößte Bundesland Österreichs?", a: ["Niederösterreich", "Wien", "Tirol", "Steiermark"], c: 0 },
    { q: "Wie heißt der bekannte Dom in Wien?", a: ["Stephansdom", "Kölner Dom", "Petersdom", "Frauenkirche"], c: 0 },
    { q: "In welcher Stadt steht die Festung Hohensalzburg?", a: ["Salzburg", "Wien", "Graz", "Innsbruck"], c: 0 },
    { q: "Welcher Vogel ist im Tiroler Wappen?", a: ["Adler", "Falke", "Taube", "Storch"], c: 0 },
    { q: "Welche Bergkette zieht durch Österreich?", a: ["Alpen", "Anden", "Pyrenäen", "Karpaten"], c: 0 },
    { q: "In welchem Monat ist der österreichische Nationalfeiertag?", a: ["Oktober", "September", "Juli", "Mai"], c: 0 },
    { q: "Welcher berühmte Psychoanalytiker lebte in Wien?", a: ["Sigmund Freud", "Albert Einstein", "Charles Darwin", "Iwan Pawlow"], c: 0 },
    { q: "In welchem Bundesland liegt Graz?", a: ["Steiermark", "Kärnten", "Tirol", "Salzburg"], c: 0 },
    { q: "In welchem Bundesland liegt Linz?", a: ["Oberösterreich", "Niederösterreich", "Steiermark", "Salzburg"], c: 0 },
    { q: "In welchem Bundesland liegt Klagenfurt?", a: ["Kärnten", "Steiermark", "Tirol", "Burgenland"], c: 0 },
    { q: "In welchem Bundesland liegt Bregenz?", a: ["Vorarlberg", "Tirol", "Salzburg", "Kärnten"], c: 0 },
    { q: "In welchem Bundesland liegt Eisenstadt?", a: ["Burgenland", "Niederösterreich", "Steiermark", "Wien"], c: 0 },
    { q: "Welcher Fluss fließt durch Salzburg?", a: ["Salzach", "Inn", "Enns", "Traun"], c: 0 },
    { q: "Welcher Fluss fließt durch Graz?", a: ["Mur", "Drau", "Donau", "Salzach"], c: 0 },
    { q: "Welcher Fluss fließt durch Innsbruck?", a: ["Inn", "Salzach", "Enns", "Mur"], c: 0 },
    { q: "Wie heißt das berühmte Schloss in Wien mit dem großen Garten?", a: ["Schönbrunn", "Neuschwanstein", "Belvedere", "Hofburg"], c: 0 },
    { q: "Welche Stadt ist die zweitgrößte Österreichs?", a: ["Graz", "Linz", "Salzburg", "Innsbruck"], c: 0 },
    { q: "In welchem Bundesland liegt der Wörthersee?", a: ["Kärnten", "Steiermark", "Salzburg", "Tirol"], c: 0 },
    { q: "Welcher Pass verbindet Österreich mit Italien über den Alpenhauptkamm?", a: ["Brenner", "Arlberg", "Semmering", "Katschberg"], c: 0 },
    { q: "Wie heißt der Nationalpark rund um den Großglockner?", a: ["Hohe Tauern", "Neusiedler See", "Gesäuse", "Thayatal"], c: 0 },
    { q: "Welcher Skiort in Tirol ist für die Abfahrt „Streif\" bekannt?", a: ["Kitzbühel", "Sölden", "Ischgl", "Saalbach"], c: 0 },
    { q: "Welches Gericht ist ein paniertes Schnitzel aus Wien?", a: ["Wiener Schnitzel", "Cordon bleu", "Backhendl", "Schweinsbraten"], c: 0 },
    { q: "Wie nennt man in Österreich Schlagsahne?", a: ["Schlagobers", "Topfen", "Germ", "Rahm"], c: 0 },
    { q: "Welche Stadt ist für Mozartkugeln berühmt?", a: ["Salzburg", "Wien", "Graz", "Linz"], c: 0 },
    { q: "Seit welchem Jahr ist Österreich Mitglied der EU?", a: ["1995", "1985", "2004", "1990"], c: 0 },
    { q: "Wer war ein österreichischer Formel-1-Weltmeister?", a: ["Niki Lauda", "Michael Schumacher", "Ayrton Senna", "Alain Prost"], c: 0 },
    { q: "Welcher österreichische Ort ist für Kristall (Swarovski) bekannt?", a: ["Wattens", "Hallstatt", "Melk", "Dürnstein"], c: 0 },
    { q: "Wie heißt Österreichs bekanntestes halbmondförmiges Frühstücksgebäck?", a: ["Kipferl", "Semmel", "Striezel", "Brezel"], c: 0 },
    { q: "Welcher Komponist schrieb den „Radetzkymarsch\"?", a: ["Johann Strauss", "Mozart", "Haydn", "Schubert"], c: 0 },
    { q: "Wie heißt der berühmteste Ball in der Wiener Staatsoper?", a: ["Opernball", "Kaiserball", "Sommerball", "Blumenball"], c: 0 },
    { q: "Welche Süßspeise ist ein dünner, gefüllter Teig, oft mit Äpfeln?", a: ["Strudel", "Sachertorte", "Palatschinke", "Kaiserschmarrn"], c: 0 },
    { q: "Wie heißt der ehemalige kaiserliche Palast im Zentrum von Wien?", a: ["Hofburg", "Schönbrunn", "Belvedere", "Albertina"], c: 0 },
    { q: "Welche zerrissene Süßspeise mit Rosinen ist eine Wiener Spezialität?", a: ["Kaiserschmarrn", "Sachertorte", "Apfelstrudel", "Buchtel"], c: 0 },
    { q: "Wie heißt der berühmte Wiener Zoo (ältester der Welt)?", a: ["Schönbrunn", "Hellabrunn", "Hagenbeck", "Tiergarten"], c: 0 },
    { q: "Welcher See liegt teils in Österreich und ist für Schilf bekannt?", a: ["Neusiedler See", "Wörthersee", "Attersee", "Traunsee"], c: 0 },
    { q: "Wie heißt das österreichische Parlament-Unterhaus?", a: ["Nationalrat", "Bundestag", "Landtag", "Reichstag"], c: 0 },
  ],
  essen: [
    { q: "Woraus wird Wein gemacht?", a: ["Trauben", "Äpfel", "Gerste", "Hopfen"], c: 0 },
    { q: "Woraus wird Brot hauptsächlich gemacht?", a: ["Mehl", "Reis", "Zucker", "Erdäpfel"], c: 0 },
    { q: "Woraus macht man Pommes frites?", a: ["Erdäpfel", "Mais", "Reis", "Bohnen"], c: 0 },
    { q: "Welches Gewürz macht Speisen scharf?", a: ["Chili", "Zimt", "Vanille", "Basilikum"], c: 0 },
    { q: "Welches Heißgetränk wird aus Blättern gemacht?", a: ["Tee", "Kakao", "Cola", "Limonade"], c: 0 },
    { q: "Welche Nuss steckt in Marzipan?", a: ["Mandel", "Walnuss", "Haselnuss", "Erdnuss"], c: 0 },
    { q: "Was ist Mozzarella?", a: ["Käse", "Wurst", "Brot", "Gemüse"], c: 0 },
    { q: "Welche Frucht hat eine harte Schale mit Flüssigkeit innen?", a: ["Kokosnuss", "Melone", "Ananas", "Mango"], c: 0 },
    { q: "Was ist Sushi typischerweise?", a: ["Reis mit Fisch", "Nudeln mit Käse", "Brot mit Wurst", "Fleischspieß"], c: 0 },
    { q: "Welches Getränk enthält Koffein?", a: ["Kaffee", "Wasser", "Milch", "Apfelsaft"], c: 0 },
    { q: "Woraus wird Guacamole hauptsächlich gemacht?", a: ["Avocado", "Tomate", "Erbse", "Gurke"], c: 0 },
    { q: "Aus welchem Getreide wird Bier hauptsächlich gebraut?", a: ["Gerste", "Reis", "Mais", "Hafer"], c: 0 },
    { q: "Welches Land ist berühmt für Pizza und Pasta?", a: ["Italien", "Frankreich", "Spanien", "Griechenland"], c: 0 },
    { q: "Woraus wird Schokolade gemacht?", a: ["Kakao", "Karamell", "Vanille", "Honig"], c: 0 },
    { q: "Welche Farbe hat ein reifer Paradeiser?", a: ["Rot", "Blau", "Lila", "Schwarz"], c: 0 },
    { q: "Wozu dient Sauerteig?", a: ["Zum Brotbacken", "Als Suppe", "Als Getränk", "Als Käse"], c: 0 },
    { q: "Aus welcher Pflanze wird das steirische „grüne Gold\"-Öl gepresst?", a: ["Kürbis", "Olive", "Sonnenblume", "Raps"], c: 0 },
    { q: "Aus welcher Milch wird Mozzarella traditionell gemacht?", a: ["Büffelmilch", "Ziegenmilch", "Schafsmilch", "Pflanzenmilch"], c: 0 },
    { q: "Welche Frucht ist gelb und krumm?", a: ["Banane", "Apfel", "Birne", "Zitrone"], c: 0 },
    { q: "Welches Gemüse lässt einen beim Schneiden oft weinen?", a: ["Zwiebel", "Karotte", "Gurke", "Paprika"], c: 0 },
    { q: "Woraus wird Käse gemacht?", a: ["Milch", "Eiern", "Mehl", "Öl"], c: 0 },
    { q: "Welches scharfe Gewürz ist rot und typisch ungarisch?", a: ["Paprika", "Zimt", "Vanille", "Muskat"], c: 0 },
    { q: "Welches Getränk wird aus gepressten Orangen gemacht?", a: ["Orangensaft", "Limonade", "Tee", "Kaffee"], c: 0 },
    { q: "Welche Nudelform ist lang und dünn?", a: ["Spaghetti", "Penne", "Fusilli", "Lasagne"], c: 0 },
    { q: "Welche Frucht ist innen rot mit Kernen und beliebt im Sommer?", a: ["Wassermelone", "Apfel", "Birne", "Kiwi"], c: 0 },
    { q: "Welches Tier liefert die Eier fürs Frühstück?", a: ["Huhn", "Kuh", "Schwein", "Schaf"], c: 0 },
    { q: "Welches lange, knusprige Weißbrot ist typisch für Frankreich?", a: ["Baguette", "Ciabatta", "Toast", "Brezel"], c: 0 },
    { q: "Welche Zutat lässt Germteig aufgehen?", a: ["Germ", "Salz", "Zucker", "Butter"], c: 0 },
    { q: "Aus welchem Tier kommt Schinken?", a: ["Schwein", "Rind", "Huhn", "Schaf"], c: 0 },
    { q: "Welches Gewürz ist süß und kommt oft in Weihnachtsgebäck (Baumrinde)?", a: ["Zimt", "Pfeffer", "Chili", "Kümmel"], c: 0 },
    { q: "Welcher Fisch wird oft geräuchert und ist orange?", a: ["Lachs", "Hering", "Forelle", "Thunfisch"], c: 0 },
    { q: "Welches Gemüse ist orange und mögen Hasen besonders?", a: ["Karotte", "Erbse", "Kraut", "Brokkoli"], c: 0 },
    { q: "Welche italienische Speise ist ein flacher Teig mit Belag?", a: ["Pizza", "Risotto", "Gnocchi", "Ravioli"], c: 0 },
    { q: "Welche Frucht ist orange, leicht schälbar und beliebt zur Weihnachtszeit?", a: ["Mandarine", "Apfel", "Kiwi", "Pflaume"], c: 0 },
    { q: "Woraus besteht Marmelade hauptsächlich?", a: ["Früchte", "Milch", "Fleisch", "Mehl"], c: 0 },
    { q: "Woraus wird Butter gemacht?", a: ["Rahm", "Öl", "Mehl", "Wasser"], c: 0 },
    { q: "Welche Frucht sagt man, hält den Arzt fern (Sprichwort)?", a: ["Apfel", "Traube", "Zitrone", "Banane"], c: 0 },
    { q: "Welche Beeren sind klein und blau und heißen in Österreich Schwarzbeeren?", a: ["Heidelbeeren", "Erdbeeren", "Himbeeren", "Brombeeren"], c: 0 },
    { q: "Welche Süßigkeit schmilzt in der Sonne und ist meist braun?", a: ["Schokolade", "Gummibärchen", "Lutscher", "Kaugummi"], c: 0 },
    { q: "Welches Getränk trinkt man heiß und macht man mit Kakao?", a: ["Heiße Schokolade", "Limonade", "Eistee", "Cola"], c: 0 },
    { q: "Was ist ein Guglhupf?", a: ["Ein Kuchen", "Eine Suppe", "Ein Braten", "Ein Salat"], c: 0 },
    { q: "Welches Gericht besteht aus rohem Fisch und Reis aus Japan?", a: ["Sushi", "Ramen", "Tempura", "Curry"], c: 0 },
    { q: "Welche Frucht wächst an Reben und gibt es grün oder blau?", a: ["Weintraube", "Kirsche", "Pflaume", "Feige"], c: 0 },
    { q: "Welche Speise besteht aus geschlagenen Eiern in der Pfanne?", a: ["Omelett", "Nudeln", "Reis", "Suppe"], c: 0 },
    { q: "Welche Suppe ist typisch aus Tomaten gemacht?", a: ["Tomatensuppe", "Gulaschsuppe", "Zwiebelsuppe", "Erbsensuppe"], c: 0 },
    { q: "Woraus wird Popcorn gemacht?", a: ["Mais", "Weizen", "Reis", "Hafer"], c: 0 },
    { q: "Welches Getränk enthält Sprudel (Kohlensäure) und ist braun?", a: ["Cola", "Milch", "Wasser", "Orangensaft"], c: 0 },
  ],
  film: [
    { q: "In welchem Film gibt es den Zauberer Gandalf?", a: ["Herr der Ringe", "Harry Potter", "Narnia", "Merlin"], c: 0 },
    { q: "Welche Firma machte „Der König der Löwen\"?", a: ["Disney", "Pixar", "DreamWorks", "Netflix"], c: 0 },
    { q: "Wie heißt der gesuchte Clownfisch?", a: ["Nemo", "Dory", "Marlin", "Bruce"], c: 0 },
    { q: "Welches grüne Wesen lebt in einem Sumpf?", a: ["Shrek", "Hulk", "Yoda", "Grinch"], c: 0 },
    { q: "Welcher Superheld hat Spinnenkräfte?", a: ["Spider-Man", "Batman", "Superman", "Iron Man"], c: 0 },
    { q: "Wie heißt die Eiskönigin in „Frozen\"?", a: ["Elsa", "Anna", "Belle", "Arielle"], c: 0 },
    { q: "Welches Studio steht für „Toy Story\"?", a: ["Pixar", "DreamWorks", "Illumination", "Ghibli"], c: 0 },
    { q: "Wie heißt der grüne Jedi-Meister in Star Wars?", a: ["Yoda", "Obi-Wan", "Anakin", "Luke"], c: 0 },
    { q: "In welchem Film fährt „Lightning McQueen\"?", a: ["Cars", "Turbo", "Speed", "Fast & Furious"], c: 0 },
    { q: "Wie heißt das Zaubererinternat bei Harry Potter?", a: ["Hogwarts", "Narnia", "Camelot", "Winterfell"], c: 0 },
    { q: "Welche Prinzessin verliert einen Schuh um Mitternacht?", a: ["Aschenputtel", "Schneewittchen", "Rapunzel", "Arielle"], c: 0 },
    { q: "Welcher Held trägt einen roten Umhang und ein „S\"?", a: ["Superman", "Batman", "Flash", "Thor"], c: 0 },
    { q: "In welchem Film gibt es einen Park mit lebenden Dinosauriern?", a: ["Jurassic Park", "King Kong", "Godzilla", "Avatar"], c: 0 },
    { q: "Welche Farbe hat der Hulk?", a: ["Grün", "Blau", "Rot", "Gelb"], c: 0 },
    { q: "Welcher Zauberer hat eine Blitznarbe auf der Stirn?", a: ["Harry Potter", "Gandalf", "Merlin", "Dumbledore"], c: 0 },
    { q: "Wie heißt der kleine weiß-blaue Astromech-Droide in Star Wars?", a: ["R2-D2", "C-3PO", "BB-8", "WALL-E"], c: 0 },
    { q: "In welchem Animationsfilm sucht ein Vater seinen Sohn im Meer?", a: ["Findet Nemo", "Arielle", "Cars", "Bambi"], c: 0 },
    { q: "Welcher Superheld ist als „der dunkle Ritter\" bekannt?", a: ["Batman", "Superman", "Hulk", "Thor"], c: 0 },
    { q: "Wie heißt das Raumschiff in Star Trek?", a: ["Enterprise", "Millennium Falcon", "Serenity", "Discovery"], c: 0 },
    { q: "Welcher Bär mag Honig in einem bekannten Kinderfilm?", a: ["Winnie Puuh", "Balu", "Yogi", "Paddington"], c: 0 },
    { q: "Wie heißt der Spielzeug-Cowboy in „Toy Story\"?", a: ["Woody", "Buzz", "Rex", "Slinky"], c: 0 },
    { q: "Wie heißt der freundliche Außerirdische mit leuchtendem Finger?", a: ["E.T.", "Yoda", "Alf", "Groot"], c: 0 },
    { q: "Welcher Film handelt von einem Löwenjungen namens Simba?", a: ["Der König der Löwen", "Madagascar", "Ice Age", "Dschungelbuch"], c: 0 },
    { q: "Mit welcher Nummer ist der Agent James Bond bekannt?", a: ["007", "008", "001", "009"], c: 0 },
    { q: "Wie heißt der Roboter, der die Erde aufräumt (Pixar)?", a: ["WALL-E", "R2-D2", "Baymax", "Optimus"], c: 0 },
    { q: "Wie heißt Batmans Heimatstadt?", a: ["Gotham City", "Metropolis", "Star City", "Central City"], c: 0 },
    { q: "Wie heißt Supermans Heimatstadt?", a: ["Metropolis", "Gotham City", "Smallville", "Star City"], c: 0 },
    { q: "Welcher Film zeigt Jack und Rose auf einem sinkenden Schiff?", a: ["Titanic", "Poseidon", "Der Sturm", "Fluch der Karibik"], c: 0 },
    { q: "Wie heißt die mutige Bogenschützin-Prinzessin bei Pixar (Merida)?", a: ["Merida", "Elsa", "Moana", "Rapunzel"], c: 0 },
    { q: "Welcher Film handelt von einer Ratte, die Koch werden will?", a: ["Ratatouille", "Cars", "Nemo", "Oben"], c: 0 },
    { q: "Welcher Superheld hat einen Hammer und ist ein Donnergott?", a: ["Thor", "Hulk", "Iron Man", "Loki"], c: 0 },
    { q: "Wie heißt das Mammut in „Ice Age\"?", a: ["Manni", "Sid", "Diego", "Scrat"], c: 0 },
    { q: "Welcher Pixar-Film handelt von einem fliegenden Haus mit Luftballons?", a: ["Oben", "Cars", "Findet Nemo", "Coco"], c: 0 },
    { q: "Wie heißt Han Solos Raumschiff in Star Wars?", a: ["Millennium Falcon", "Enterprise", "X-Wing", "Todesstern"], c: 0 },
    { q: "Welcher Zeichentrick-Kater jagt die Maus Jerry?", a: ["Tom", "Sylvester", "Garfield", "Felix"], c: 0 },
    { q: "Wie heißt der Bär im Dschungelbuch?", a: ["Balu", "Winnie", "Yogi", "Bruno"], c: 0 },
    { q: "Welcher Marvel-Held trägt ein rot-weiß-blaues Schild?", a: ["Captain America", "Iron Man", "Thor", "Hulk"], c: 0 },
    { q: "Welcher Film spielt auf dem blauen Planeten Pandora?", a: ["Avatar", "Star Wars", "Interstellar", "Guardians"], c: 0 },
    { q: "Welche gelbe Zeichentrickfamilie lebt in Springfield?", a: ["Die Simpsons", "Familie Feuerstein", "Griffins", "South Park"], c: 0 },
    { q: "Wie heißt der Superheld, der als Tony Stark eine Eisenrüstung trägt?", a: ["Iron Man", "Batman", "Thor", "Ant-Man"], c: 0 },
    { q: "Wie heißt Elsas Schwester in „Die Eiskönigin\"?", a: ["Anna", "Belle", "Aurora", "Jasmin"], c: 0 },
    { q: "Welcher Film handelt von einem Clownfisch-Vater, der seinen Sohn sucht?", a: ["Findet Nemo", "Der kleine Hai", "Arielle", "Bambi"], c: 0 },
    { q: "Welche Firma produziert die „Minions\"?", a: ["Illumination", "Pixar", "DreamWorks", "Disney"], c: 0 },
    { q: "Welcher grüne Oger hat einen sprechenden Esel als Freund?", a: ["Shrek", "Hulk", "Grinch", "Fiona"], c: 0 },
    { q: "Wie heißt das Zauberer-Internat in den Harry-Potter-Filmen?", a: ["Hogwarts", "Beauxbatons", "Durmstrang", "Camelot"], c: 0 },
    { q: "Welcher Film handelt von Spielzeugen, die lebendig werden?", a: ["Toy Story", "Cars", "Shrek", "Madagascar"], c: 0 },
    { q: "Wie heißt der Held mit Peitsche und Hut auf Schatzsuche?", a: ["Indiana Jones", "James Bond", "Lara Croft", "Zorro"], c: 0 },
  ],
  schwer: [
    { q: "Welches chemische Element hat die Ordnungszahl 1?", a: ["Wasserstoff", "Helium", "Sauerstoff", "Kohlenstoff"], c: 0 },
    { q: "Welcher Planet dreht sich am schnellsten um sich selbst?", a: ["Jupiter", "Erde", "Mars", "Merkur"], c: 0 },
    { q: "Welches Land hat die meisten Einwohner?", a: ["Indien", "China", "USA", "Indonesien"], c: 0 },
    { q: "Wofür steht die Abkürzung „CPU\"?", a: ["Central Processing Unit", "Computer Power Unit", "Central Program Unit", "Core Personal Unit"], c: 0 },
    { q: "Wie nennt man die kleinste Einheit eines chemischen Elements?", a: ["Atom", "Molekül", "Zelle", "Ion"], c: 0 },
    { q: "Welches Metall ist bei Raumtemperatur flüssig?", a: ["Quecksilber", "Eisen", "Blei", "Kupfer"], c: 0 },
    { q: "Wie viele Zeitzonen hat Russland ungefähr?", a: ["11", "5", "24", "3"], c: 0 },
    { q: "Welcher Ozean ist der tiefste?", a: ["Pazifik", "Atlantik", "Indischer", "Arktischer"], c: 0 },
    { q: "Welche Sprache hat weltweit die meisten Muttersprachler?", a: ["Mandarin-Chinesisch", "Englisch", "Spanisch", "Hindi"], c: 0 },
    { q: "Welches Vitamin bildet der Körper mithilfe von Sonnenlicht?", a: ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"], c: 0 },
    { q: "Wie heißt das größte Organ des menschlichen Körpers?", a: ["Haut", "Leber", "Lunge", "Darm"], c: 0 },
    { q: "In welchem Land liegt Machu Picchu?", a: ["Peru", "Mexiko", "Chile", "Bolivien"], c: 0 },
    { q: "Welcher Kontinent hat die meisten Länder?", a: ["Afrika", "Asien", "Europa", "Südamerika"], c: 0 },
    { q: "Was ist die chemische Formel für Kochsalz?", a: ["NaCl", "H₂O", "CO₂", "KCl"], c: 0 },
    { q: "Welcher ist der größte Planet im Sonnensystem?", a: ["Jupiter", "Saturn", "Neptun", "Erde"], c: 0 },
    { q: "Welcher Physiker ist für die Unschärferelation bekannt?", a: ["Heisenberg", "Newton", "Faraday", "Curie"], c: 0 },
    { q: "Auf welchem Erdteil liegt der tiefste Landpunkt (Totes Meer)?", a: ["Asien", "Afrika", "Europa", "Amerika"], c: 0 },
    { q: "Welche Blutgruppe gilt als Universalspender?", a: ["0 negativ", "AB positiv", "A positiv", "B negativ"], c: 0 },
    { q: "Wer formulierte die drei Bewegungsgesetze der Mechanik?", a: ["Newton", "Einstein", "Galilei", "Bohr"], c: 0 },
    { q: "Welche Hauptstadt liegt am höchsten über dem Meer?", a: ["La Paz", "Quito", "Bogotá", "Kathmandu"], c: 0 },
    { q: "In welchem Jahr sank die Titanic?", a: ["1912", "1905", "1920", "1898"], c: 0 },
    { q: "Welches Tier hat mehrere „Herzen\" (Aortenbögen)?", a: ["Regenwurm", "Frosch", "Fisch", "Schnecke"], c: 0 },
    { q: "Welcher Wissenschaftler bekam den Physik-Nobelpreis für den Photoeffekt?", a: ["Einstein", "Planck", "Bohr", "Tesla"], c: 0 },
    { q: "Wie lautet die Kreiszahl Pi auf zwei Nachkommastellen?", a: ["3,14", "3,41", "3,12", "3,16"], c: 0 },
    { q: "Welche Einheit misst den elektrischen Widerstand?", a: ["Ohm", "Volt", "Ampere", "Watt"], c: 0 },
    { q: "Welche Einheit misst die Frequenz?", a: ["Hertz", "Newton", "Joule", "Pascal"], c: 0 },
    { q: "Welcher Planet hat die meisten bekannten Monde?", a: ["Saturn", "Jupiter", "Uranus", "Neptun"], c: 0 },
    { q: "Wie nennt man die Sprache der alten Römer?", a: ["Latein", "Griechisch", "Etruskisch", "Aramäisch"], c: 0 },
    { q: "Welches Organ entgiftet den Körper hauptsächlich?", a: ["Leber", "Herz", "Lunge", "Milz"], c: 0 },
    { q: "Welche mathematische Konstante ist ungefähr 2,718?", a: ["Eulersche Zahl (e)", "Pi", "Goldener Schnitt", "Wurzel 2"], c: 0 },
    { q: "Welcher Wissenschaftler stellte das Periodensystem der Elemente auf?", a: ["Mendelejew", "Bohr", "Dalton", "Curie"], c: 0 },
    { q: "In welchem Jahr begann die Französische Revolution?", a: ["1789", "1776", "1804", "1815"], c: 0 },
    { q: "Wie viele Kammern hat das menschliche Herz?", a: ["4", "2", "3", "5"], c: 0 },
    { q: "Welcher Fluss ist der längste in Südamerika?", a: ["Amazonas", "Paraná", "Orinoco", "Rio Grande"], c: 0 },
    { q: "Welche Blutgefäße transportieren Blut zum Herzen zurück?", a: ["Venen", "Arterien", "Kapillaren", "Nerven"], c: 0 },
    { q: "Wie viele Grad hat ein rechter Winkel?", a: ["90", "45", "180", "60"], c: 0 },
    { q: "Welche der Zahlen ist eine Primzahl?", a: ["53", "51", "55", "57"], c: 0 },
    { q: "Wie heißt der Vorgang, bei dem Pflanzen aus Licht Energie gewinnen?", a: ["Photosynthese", "Verdauung", "Osmose", "Gärung"], c: 0 },
    { q: "Welcher Planet ist der kälteste im Sonnensystem?", a: ["Neptun", "Mars", "Saturn", "Uranus"], c: 0 },
    { q: "Wer entwickelte das Telefon (Patent 1876)?", a: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"], c: 0 },
    { q: "Wie heißt der größte Mond des Saturn?", a: ["Titan", "Europa", "Io", "Ganymed"], c: 0 },
    { q: "Welcher Teil des Atoms ist negativ geladen?", a: ["Elektron", "Proton", "Neutron", "Kern"], c: 0 },
    { q: "Wie nennt man versteinertes Baumharz?", a: ["Bernstein", "Granit", "Marmor", "Quarz"], c: 0 },
    { q: "In welchem Organ findet der Gasaustausch statt?", a: ["Lunge", "Leber", "Herz", "Magen"], c: 0 },
    { q: "Welcher Philosoph prägte den Satz „Cogito ergo sum\"?", a: ["Descartes", "Platon", "Kant", "Sokrates"], c: 0 },
    { q: "Wie lautet das chemische Symbol für Eisen?", a: ["Fe", "Ei", "Ir", "Fr"], c: 0 },
    { q: "Welcher Physiker ist für die Relativitätstheorie bekannt?", a: ["Einstein", "Newton", "Hawking", "Bohr"], c: 0 },
    { q: "Welches Gas hat die chemische Formel CO₂?", a: ["Kohlendioxid", "Sauerstoff", "Stickstoff", "Methan"], c: 0 },
    { q: "Wie viele bekannte Elemente hat das Periodensystem ungefähr?", a: ["118", "92", "150", "80"], c: 0 },
    { q: "Wie nennt man die Wissenschaft von Erdbeben?", a: ["Seismologie", "Geologie", "Vulkanologie", "Ökologie"], c: 0 },
    { q: "Welcher längste Knochen befindet sich im menschlichen Bein?", a: ["Oberschenkelknochen", "Schienbein", "Wadenbein", "Kniescheibe"], c: 0 },
    { q: "Welche geometrische Form hat 6 quadratische Flächen?", a: ["Würfel", "Pyramide", "Kegel", "Zylinder"], c: 0 },
  ],
};
export const Q_CAT_KEYS = Object.keys(Q_CATS);

// Menschlich lesbares Label je Kategorie (für Client-Auswahl/Hinweis).
export const Q_CAT_LABELS = {
  allgemein: "Allgemein", geografie: "Geografie", natur: "Natur & Tiere",
  wissenschaft: "Wissenschaft", geschichte: "Geschichte", sport: "Sport",
  kultur: "Kultur", oesterreich: "Österreich", essen: "Essen & Trinken",
  film: "Film & Serien", schwer: "Kopfnüsse",
};

// Schwierigkeit einer Frage: eigenes `d`-Feld > Kategorie-Grundwert > Mittel.
export function questionDifficulty(item, catKey) {
  if (item && (item.d === 1 || item.d === 2 || item.d === 3)) return item.d;
  return Q_CAT_DIFF[catKey] || 2;
}

// Fragen-Pool aus gewählten Kategorien (leer = alle) und optionaler Schwierigkeit
// (0/undefined = alle). Jede Frage bekommt `cat` (Kategorie-Key) und `diff` (Stufe)
// angehängt, damit Client/Server sie ohne erneutes Nachschlagen anzeigen können.
export function questionPool(cats, diff = 0) {
  const keys = (Array.isArray(cats) && cats.length) ? cats.filter(k => Q_CATS[k]) : Q_CAT_KEYS;
  const use = keys.length ? keys : Q_CAT_KEYS;
  const out = [];
  for (const k of use) for (const q of Q_CATS[k]) {
    const d = questionDifficulty(q, k);
    if (diff && d !== diff) continue;
    out.push({ q: q.q, a: q.a, c: q.c, cat: k, diff: d });
  }
  return out;
}

// n verschiedene Fragen zufällig ziehen (Objekt-Referenzen). rnd injizierbar.
export function pickQuestions(pool, n, rnd = Math.random) {
  const out = [], used = new Set(); let guard = 0;
  const cap = Math.min(n, pool.length);
  while (out.length < cap && guard++ < 5000) {
    const i = Math.floor(rnd() * pool.length);
    if (!used.has(i)) { used.add(i); out.push(pool[i]); }
  }
  return out;
}

// Optionen mischen (Fisher-Yates) und den neuen Index der Lösung zurückgeben.
// rnd injizierbar → deterministisch testbar. Verändert das Original NICHT.
export function shuffleOptions(question, rnd = Math.random) {
  const opts = question.a.slice();
  const correctText = question.a[question.c];
  for (let i = opts.length - 1; i > 0; i--) {
    const j = Math.floor(rnd() * (i + 1));
    [opts[i], opts[j]] = [opts[j], opts[i]];
  }
  return { options: opts, correct: opts.indexOf(correctText) };
}

// Punkte für eine Antwort: nur bei richtig. 100 Basis + Tempo-Bonus (früher =
// mehr, bis +100). Falsch/keine Antwort = 0.
export function answerGain({ remain, total = Q_TURN, correct }) {
  if (!correct) return 0;
  const speed = Math.round((Math.max(0, remain) / total) * 100);
  return 100 + speed;
}
